# Site settings
author: Mona Javed 
title: Future Programmer
header-img: img/home-bg.png
email: monajaved93@gmail.com
copyright_name: Mona Javed 
description: > # this means to ignore newlines until "baseurl:"
  My journey towards programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  monajaved

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
